name: Rebase
on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - 'base/**'
    - 'apps/**'
  pull_request:
    paths:
    - 'base/**'
    - 'apps/**'

jobs:
  rebase:
    runs-on: self-hosted
    steps:
      - uses: peter-evans/rebase@v1
        with:
          base: master
