name: Get latest versions

on:
  workflow_dispatch:
  schedule:
  - cron: "*/30 * * * *"

jobs:
  get-version:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.CR_PAT }}
        fetch-depth: 0

    - name: Run Commands
      run: |
        echo "Fetch new Versions"
        if test -f "./.github/version.sh"; then
           bash "./.github/version.sh"
        fi
        echo "Check Mixed Endings"
        if test -f "./.github/crlf.sh"; then
           bash "./.github/crlf.sh"
        fi
        echo "Repack Repo"
        if test -f "./.github/repack.sh"; then
           bash "./.github/repack.sh"
        fi
      env:
        username: ${{ github.actor }}
        token: ${{ secrets.CR_PAT }}

  contrib:
    runs-on: ubuntu-latest
    needs: get-version
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.CR_PAT }}

    - uses: BobAnkh/add-contributors@master
      with:
        REPO_NAME: 'dockserver/container'
        CONTRIBUTOR: '### Contributors'
        COLUMN_PER_ROW: '4'
        ACCESS_TOKEN: ${{ secrets.CR_PAT }}
        IMG_WIDTH: '100'
        FONT_SIZE: '14'
        PATH: '/README.md'
        COMMIT_MESSAGE: 'docs(README): update contributors'
        AVATAR_SHAPE: 'square'
