name: Get latest versions

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */2 * * *"

jobs:
  get-version:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.CR_PAT }}
        fetch-depth: 1
    - name: Fetch new Versions
      run: |
        if test -f "./.github/version.sh"; then
           bash "./.github/version.sh"
        fi
