name: Get latest versions

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */2 * * *"

jobs:
  get-version:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.CR_PAT }}
        fetch-depth: 1
    - name: Fetch new overlay versions
      run: |
        find ./base -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | while read app; do
          if test -f "./base/${app}/latest-overlay.sh"; then
            version=$(bash "./base/${app}/latest-overlay.sh")
            if [[ ! -z "${version}" || "${version}" != "null" ]]; then
              echo "${version}" | tee "./base/${app}/OVERLAY_VERSION" > /dev/null
              echo "${app} ${version}"
            fi
          fi
        done
    - name: Fetch new base versions
      run: |
        find ./base -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | while read app; do
          if test -f "./base/${app}/latest-version.sh"; then
            version=$(bash "./base/${app}/latest-version.sh")
            if [[ ! -z "${version}" || "${version}" != "null" ]]; then
              echo "${version}" | tee "./base/${app}/VERSION" > /dev/null
              echo "${app} ${version}"
            fi
          fi
        done
    - name: Fetch new app versions
      run: |
        find ./apps -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | while read app; do
          if test -f "./apps/${app}/latest-version.sh"; then
            version=$(bash "./apps/${app}/latest-version.sh")
            if [[ ! -z "${version}" || "${version}" != "null" ]]; then
              echo "${version}" | tee "./apps/${app}/VERSION" > /dev/null
              echo "${app} ${version}"
            fi
          fi
        done
    - name: Add, commit and push to applications version file
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -sam "charges: add new release versions" || exit 0
          git push
        fi
