name: Get latest versions

on:
  workflow_dispatch:
  schedule:
  - cron: "*/30 * * * *"

jobs:
  get-version:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.CR_PAT }}
        fetch-depth: 1

    - name: Test API
      run: |
        API=$(curl -H "Authorization: token ${{ secrets.CR_PAT }}" -X GET https://api.github.com/rate_limit \
             | jq --raw-output '.rate.limit')
        if [[ $API -gt 10 ]]; then
           echo " $API okay "
        elif [[ $API -lt 10 ]]; then
             echo " $API busted " && exit 0
        else
             echo " no reponse from Github API ? Maybe down or busted " && exit 0
        fi

    - name: Fetch new Versions
      run: |
        if test -f "./.github/version.sh"; then
           bash "./.github/version.sh"
        fi
